name: Deploy
on:
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Replace API key
          run: sed -i "s/YOUR_API_KEY_HERE/${{ secrets.REFLCT_API_KEY }}/g"
   config.js
        - uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./
